### ISSUE TITLE
result of decode modeling

### ISSUE THREAD

**Issue by troore** [abhibambhaniya/GenZ-LLM-Analyzer#3]
Hi @abhibambhaniya,

Thanks for the great work~

I have one quick question on the result of `decode_modeling` in llm_decode.py: does the latency mean latency per token? Because it calculates the average of the first and the lask token.

troore

**Comment by abhibambhaniya** [comment]
Hi toore,

Yes, your understanding is correct; decode token latency is the latency of the average of the first and last token. The idea is that the average would approximate the decode time for all tokens.

Please let me know if you any questions.
