### ISSUE TITLE
[bug] incorrect unit in funcion get_offload_system when calculating new_offchip_BW

### ISSUE THREAD

**Issue by troore** [abhibambhaniya/GenZ-LLM-Analyzer#4]
Hi @abhibambhaniya,

I found one suspicious bug in function `get_offload_system`, in file `GenZ/LLM_inference/utils.py`. The unit of `total_memory_req` passed to this function seems to be `MB`, while `total_device_memory` is clearly `GB` as commented by the first line of this function.

It was found when I created a case to show how offload would affect performance, and the offloaded memory size always dominates. I made a quick fixing by simply dividing `total_memory_req` by 1024, as did on `total_device_memory`. 

Could you help double check?

Thanks,
troore

**Comment by abhibambhaniya** [comment]
Hi toore, 

Thanks for pointing out the bug. Yes, your fix is correct. I have also corrected the bug in the [commit](https://github.com/abhibambhaniya/GenZ-LLM-Analyzer/commit/7e90d427c50b3ea6b78059aa2bc1724253100840) .

Please, let me know if you have any more questions.

Thanks,
Abhimanyu
